{{- $workloads := include "at.workloads" . | fromYaml }}
{{- range $key, $ing := .Values.ingresses }}
{{- if ne $ing.enabled false }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
{{ include "at.metadata" (dict "ctx" $ "name" (include "at.resourceName" (list $ $key)) "annotations" $ing.annotations) }}
spec:
  {{- with $ing.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with $ing.tls }}
  tls:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  rules:
    {{- range $ing.hosts }}
    - host: {{ tpl .host $ | quote }}
      http:
        paths:
          {{- range .paths }}
          {{- $svc := include "at.lookupService" (dict "workloads" $workloads "ref" . "from" (printf "ingresses.%s" $key)) | fromYaml }}
          - path: {{ .path | default "/" }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "at.serviceName" (list $ .workload .service) }}
                port:
                  number: {{ include "at.servicePort" (dict "svc" $svc "port" .port "ref" (printf "ingresses.%s" $key)) }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}
