apiVersion: v2
name: app-template
description: Compose-style chart - workloads, services, routes, datastores and policies from values alone
type: application
version: 0.3.1
home: https://github.com/nulcell/charts
sources:
  - https://github.com/nulcell/charts
keywords:
  - app-template
  - common
maintainers:
  - name: Salimon Ayanleye
    email: cloud@nulcell.com
